name: example

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  envied: ^0.3.0
  openai_api: any
dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0

dependency_overrides:
  openai_api:
    path: ../
